### PR TITLE
Support hapi 11

### PR DESCRIPTION
**Pull request by mandado**

### CODE REVIEW

**Comment by Martindelataille** [comment]
Need it too. Thanks

**Comment by mandado** [comment]
@Martindelataille i hope my updates are correct to accept pull request hehehe.
@gergoerdosi is correct my changes to accept pull request ?

**Comment by gergoerdosi** [comment]
@mandado I think vision needs to be added to the peerDependencies too.

**Comment by gergoerdosi** [comment]
@Martindelataille Thanks! I'm planning to do some refactor which will result in a new major version expected in a day or two. I will release this change as part of it.

**Comment by mandado** [comment]
@gergoerdosi what the changes in new version ?

**Comment by gergoerdosi** [comment]
Mostly dropping support for node 0.10 and 0.12. I would also like to support multiple hapi versions (10, 11, etc). There shouldn't be any changes in the API. Is there anything you would like to see in the new version?

**Comment by mandado** [comment]
@gergoerdosi so i think an function type ```json.set``` but is to array and don't need the first param required.

Example:

```
json.setArray([{ id : 1},{ id : 2},{ id : 3}]);
```
returns: ``` [{ id : 1},{ id : 2},{ id : 3}]```

or

```
json.setArray('ids', [{ id : 1},{ id : 2},{ id : 3}]);
```
returns: ``` { "ids" : [{ id : 1},{ id : 2},{ id : 3}] }```

what do you think?  I don't see this feature in api hehe.

**Comment by Martindelataille** [comment]
@gergoerdosi Thanks for your amazing work. Maybe a new features will be to be able to merge json view.
something like 
`return reply.view({'a', 'b'}, { a: objectA, b: objectB });`

and will result in
```javascript
{
 a: {
  name: 'a'
 },
 b: {
  name: 'b'
 }
}
```

**Comment by gergoerdosi** [comment]
@mandado I will see how to make that part easier.

@Martindelataille What's the use case for this? Can you show a real world example?

**Comment by Martindelataille** [comment]
@gergoerdosi For example:
```javascript
json.set('pagination', json.partial('pagination', { pagination: pagination }));
json.set('articles', json.array(articles, function (json, article) {
    json.set('', json.partial('article', { article: article }));
}));
```

I use it on templates which need pagination.

**Comment by mandado** [comment]
@gergoerdosi I can help you ?  I'm thinking make something related this and show to you, what do you that think ?

**Comment by gergoerdosi** [comment]
@Martindelataille Got it. Yes, we need something similar too, but not sure how to do it. I can't change the `reply.view()` interface. It accepts three parameters where the first one is the name of the template and the second is the context. The interface wasn't really designed to support multiple templates.

https://github.com/hapijs/vision/blob/master/API.md#the-view-handler

**Comment by gergoerdosi** [comment]
@mandado Yes, of course!

**Comment by mandado** [comment]
@gergoerdosi thanks! :)

**Pull request merged**
