### PR TITLE
draft: added feature setArray

### PR DESCRIPTION
**Pull request by mandado**
@gergoerdosi what do you think ?

### CODE REVIEW

**Comment by gergoerdosi** [comment]
As I can see you added 4 tests, but only 1 of them uses `setArray()`. So what's the benefit of adding `setArray()`? Also, what is supposed to be the difference between `json.set(['example'])` and `json.setArray(['example])`?

You can run tests by executing `npm test`.

**Comment by mandado** [comment]
I'm think will not be necessary to add the setArray feature, but don't have difference.

**Comment by mandado** [comment]
@gergoerdosi I think it makes more sense to discard this pull request.

**Comment by gergoerdosi** [comment]
I see. What do you think about making `json.array()` a bit more clever? So you could do things like:

```
json.set('tags', json.array(tags))
```

In this case `json.array()` would just enforce that the result is an array, but would not require a callback for iteration. If you passed `null` or `undefined` as the value of `tags`, it would be converted to an empty array.

**Comment by mandado** [comment]
@gergoerdosi  Good idea!, i would like to make this change. :+1:

**Comment by gergoerdosi** [comment]
Sure, go ahead!

**Pull request closed without merging**
